###
GET http://localhost:5000/users
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJuYW1lIjoiQnVuZyB0b3dlbCIsImlhdCI6MTcxODE3ODM1MCwiZXhwIjoxNzE4MTc4MzY1fQ.brHk8uXz6feN7NQlZW8-zCqWzyPL5D07qgv-CUh3P6g



###
POST http://localhost:5000/users
Content-Type: application/json

{
  "username":"topik",
  "email":"taufik58@gmail.com",
  "nama_kelas":"pancasila",
  "password":"123456",
  "confPassword":"123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "username":"bung towel",
  "password":"reset"
}


###
GET http://localhost:5000/token


###
DELETE http://localhost:5000/logout